\doxysection{numpy.\+exceptions.\+Too\+Hard\+Error Class Reference}
\hypertarget{classnumpy_1_1exceptions_1_1TooHardError}{}\label{classnumpy_1_1exceptions_1_1TooHardError}\index{numpy.exceptions.TooHardError@{numpy.exceptions.TooHardError}}


Inheritance diagram for numpy.\+exceptions.\+Too\+Hard\+Error\+:
% FIG 0


Collaboration diagram for numpy.\+exceptions.\+Too\+Hard\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}max_work was exceeded.

This is raised whenever the maximum number of candidate solutions
to consider specified by the ``max_work`` parameter is exceeded.
Assigning a finite number to max_work may have caused the operation
to fail.
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{numpy_2exceptions_8py_source_l00085}{85}} of file \mbox{\hyperlink{numpy_2exceptions_8py_source}{exceptions.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/numpy/exceptions.\+py\end{DoxyCompactItemize}
