\doxysection{pip.\+\_\+internal.\+exceptions.\+Hash\+Error Class Reference}
\hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError}{}\label{classpip_1_1__internal_1_1exceptions_1_1HashError}\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Hash\+Error\+:
% FIG 0


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Hash\+Error\+:
% FIG 1
\doxysubsubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a8b1a0890122218544dd1a3e23c416431}{body}} (self)
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a455e73a1648e11e2d124cf5bd30f97f3}{\+\_\+\+\_\+str\+\_\+\+\_\+}} (self)
\end{DoxyCompactItemize}
\doxysubsubsection*{Static Public Attributes}
\begin{DoxyCompactItemize}
\item 
Optional \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_af3c50ea4f7da6636a64b938cda7052c9}{req}} = None
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_ad051d7f7e98b51e235a5bc4ca17b302c}{head}} = "{}"{}
\item 
int \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a81cbe1b130a39b1625d11456709e1047}{order}} = -\/1
\end{DoxyCompactItemize}
\doxysubsubsection*{Protected Member Functions}
\begin{DoxyCompactItemize}
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a17be3100accef085731b0299b3528866}{\+\_\+requirement\+\_\+name}} (self)
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}A failure to verify a package against known-good hashes

:cvar order: An int sorting hash exception classes by difficulty of
    recovery (lower being harder), so the user doesn't bother fretting
    about unpinned packages when he has deeper issues, like VCS
    dependencies, to deal with. Also keeps error reports in a
    deterministic order.
:cvar head: A section heading for display above potentially many
    exceptions of this kind
:ivar req: The InstallRequirement that triggered this error. This is
    pasted on after the exception is instantiated, because it's not
    typically available earlier.
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00444}{444}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



\doxysubsection{Member Function Documentation}
\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_a455e73a1648e11e2d124cf5bd30f97f3}\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!\_\_str\_\_@{\_\_str\_\_}}
\index{\_\_str\_\_@{\_\_str\_\_}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{\_\_str\_\_()}{\_\_str\_\_()}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1HashError_a455e73a1648e11e2d124cf5bd30f97f3} 
 str pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+\_\+\+\_\+str\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self}{}\end{DoxyParamCaption})}



Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00477}{477}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.

\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_a17be3100accef085731b0299b3528866}\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!\_requirement\_name@{\_requirement\_name}}
\index{\_requirement\_name@{\_requirement\_name}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{\_requirement\_name()}{\_requirement\_name()}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1HashError_a17be3100accef085731b0299b3528866} 
 str pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+\_\+requirement\+\_\+name (\begin{DoxyParamCaption}\item[{}]{self}{}\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [protected]}}

\begin{DoxyVerb}Return a description of the requirement that triggered me.

This default implementation returns long description of the req, with
line numbers
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00480}{480}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.

\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_a8b1a0890122218544dd1a3e23c416431}\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!body@{body}}
\index{body@{body}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{body()}{body()}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1HashError_a8b1a0890122218544dd1a3e23c416431} 
 str pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+body (\begin{DoxyParamCaption}\item[{}]{self}{}\end{DoxyParamCaption})}

\begin{DoxyVerb}Return a summary of me for display under the heading.

This default implementation simply prints a description of the
triggering requirement.

:param req: The InstallRequirement that provoked this error, with
    its link already populated by the resolver's _populate_link().
\end{DoxyVerb}
 

Reimplemented in \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a24c9ffc7b9a48c74ac53439d56a05dc6}{pip.\+\_\+internal.\+exceptions.\+Hash\+Mismatch}}, and \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashMissing_afe037f000b99010da015d0209089d6dd}{pip.\+\_\+internal.\+exceptions.\+Hash\+Missing}}.



Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00465}{465}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



\doxysubsection{Member Data Documentation}
\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_ad051d7f7e98b51e235a5bc4ca17b302c}\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!head@{head}}
\index{head@{head}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{head}{head}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1HashError_ad051d7f7e98b51e235a5bc4ca17b302c} 
str pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+head = "{}"{}\hspace{0.3cm}{\ttfamily [static]}}



Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00462}{462}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



Referenced by \mbox{\hyperlink{generic_8py_source_l02266}{pandas.\+core.\+generic.\+NDFrame.\+\_\+repr\+\_\+data\+\_\+resource\+\_\+()}}.

\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_a81cbe1b130a39b1625d11456709e1047}\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!order@{order}}
\index{order@{order}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{order}{order}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1HashError_a81cbe1b130a39b1625d11456709e1047} 
int pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+order = -\/1\hspace{0.3cm}{\ttfamily [static]}}



Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00463}{463}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



Referenced by \mbox{\hyperlink{multioutput_8py_source_l00744}{sklearn.\+multioutput.\+\_\+\+Base\+Chain.\+fit()}}, \mbox{\hyperlink{__ode_8py_source_l00944}{scipy.\+integrate.\+\_\+ode.\+vode.\+reset()}}, \mbox{\hyperlink{__ode_8py_source_l01046}{scipy.\+integrate.\+\_\+ode.\+zvode.\+reset()}}, \mbox{\hyperlink{__polynomial_8py_source_l00388}{sklearn.\+preprocessing.\+\_\+polynomial.\+Polynomial\+Features.\+transform()}}, and \mbox{\hyperlink{__polynomial_8py_source_l00935}{sklearn.\+preprocessing.\+\_\+polynomial.\+Spline\+Transformer.\+transform()}}.

\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_af3c50ea4f7da6636a64b938cda7052c9}\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!req@{req}}
\index{req@{req}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{req}{req}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1HashError_af3c50ea4f7da6636a64b938cda7052c9} 
pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+req = None\hspace{0.3cm}{\ttfamily [static]}}



Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00461}{461}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



Referenced by \mbox{\hyperlink{req__install_8py_source_l00391}{pip.\+\_\+internal.\+req.\+req\+\_\+install.\+Install\+Requirement.\+\_\+set\+\_\+requirement()}}, \mbox{\hyperlink{req__install_8py_source_l00744}{pip.\+\_\+internal.\+req.\+req\+\_\+install.\+Install\+Requirement.\+archive()}}, \mbox{\hyperlink{req__install_8py_source_l00431}{pip.\+\_\+internal.\+req.\+req\+\_\+install.\+Install\+Requirement.\+check\+\_\+if\+\_\+exists()}}, \mbox{\hyperlink{req__install_8py_source_l00229}{pip.\+\_\+internal.\+req.\+req\+\_\+install.\+Install\+Requirement.\+format\+\_\+debug()}}, \mbox{\hyperlink{req__install_8py_source_l00333}{pip.\+\_\+internal.\+req.\+req\+\_\+install.\+Install\+Requirement.\+from\+\_\+path()}}, \mbox{\hyperlink{req__install_8py_source_l00270}{pip.\+\_\+internal.\+req.\+req\+\_\+install.\+Install\+Requirement.\+is\+\_\+pinned()}}, \mbox{\hyperlink{req__install_8py_source_l00557}{pip.\+\_\+internal.\+req.\+req\+\_\+install.\+Install\+Requirement.\+prepare\+\_\+metadata()}}, and \mbox{\hyperlink{req__install_8py_source_l00706}{pip.\+\_\+internal.\+req.\+req\+\_\+install.\+Install\+Requirement.\+uninstall()}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
