\doxysection{pandas.\+errors.\+Possible\+Data\+Loss\+Error Class Reference}
\hypertarget{classpandas_1_1errors_1_1PossibleDataLossError}{}\label{classpandas_1_1errors_1_1PossibleDataLossError}\index{pandas.errors.PossibleDataLossError@{pandas.errors.PossibleDataLossError}}


Inheritance diagram for pandas.\+errors.\+Possible\+Data\+Loss\+Error\+:
% FIG 0


Collaboration diagram for pandas.\+errors.\+Possible\+Data\+Loss\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Exception raised when trying to open a HDFStore file when already opened.

Examples
--------
>>> store = pd.HDFStore('my-store', 'a') # doctest: +SKIP
>>> store.open("w") # doctest: +SKIP
... # PossibleDataLossError: Re-opening the file [my-store] with mode [a]...
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pandas_2errors_2____init_____8py_source_l00662}{662}} of file \mbox{\hyperlink{pandas_2errors_2____init_____8py_source}{\+\_\+\+\_\+init\+\_\+\+\_\+.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pandas/errors/\+\_\+\+\_\+init\+\_\+\+\_\+.\+py\end{DoxyCompactItemize}
