\doxysection{pandas.\+errors.\+Setting\+With\+Copy\+Error Class Reference}
\hypertarget{classpandas_1_1errors_1_1SettingWithCopyError}{}\label{classpandas_1_1errors_1_1SettingWithCopyError}\index{pandas.errors.SettingWithCopyError@{pandas.errors.SettingWithCopyError}}


Inheritance diagram for pandas.\+errors.\+Setting\+With\+Copy\+Error\+:
% FIG 0


Collaboration diagram for pandas.\+errors.\+Setting\+With\+Copy\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Exception raised when trying to set on a copied slice from a ``DataFrame``.

The ``mode.chained_assignment`` needs to be set to set to 'raise.' This can
happen unintentionally when chained indexing.

For more information on evaluation order,
see :ref:`the user guide<indexing.evaluation_order>`.

For more information on view vs. copy,
see :ref:`the user guide<indexing.view_versus_copy>`.

Examples
--------
>>> pd.options.mode.chained_assignment = 'raise'
>>> df = pd.DataFrame({'A': [1, 1, 1, 2, 2]}, columns=['A'])
>>> df.loc[0:3]['A'] = 'a' # doctest: +SKIP
... # SettingWithCopyError: A value is trying to be set on a copy of a...
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pandas_2errors_2____init_____8py_source_l00411}{411}} of file \mbox{\hyperlink{pandas_2errors_2____init_____8py_source}{\+\_\+\+\_\+init\+\_\+\+\_\+.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pandas/errors/\+\_\+\+\_\+init\+\_\+\+\_\+.\+py\end{DoxyCompactItemize}
