\doxysection{pandas.\+errors.\+Unsupported\+Function\+Call Class Reference}
\hypertarget{classpandas_1_1errors_1_1UnsupportedFunctionCall}{}\label{classpandas_1_1errors_1_1UnsupportedFunctionCall}\index{pandas.errors.UnsupportedFunctionCall@{pandas.errors.UnsupportedFunctionCall}}


Inheritance diagram for pandas.\+errors.\+Unsupported\+Function\+Call\+:
% FIG 0


Collaboration diagram for pandas.\+errors.\+Unsupported\+Function\+Call\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Exception raised when attempting to call a unsupported numpy function.

For example, ``np.cumsum(groupby_object)``.

Examples
--------
>>> df = pd.DataFrame({"A": [0, 0, 1, 1],
...                    "B": ["x", "x", "z", "y"],
...                    "C": [1, 2, 3, 4]}
...                   )
>>> np.cumsum(df.groupby(["A"]))
Traceback (most recent call last):
UnsupportedFunctionCall: numpy operations are not valid with groupby.
Use .groupby(...).cumsum() instead
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pandas_2errors_2____init_____8py_source_l00072}{72}} of file \mbox{\hyperlink{pandas_2errors_2____init_____8py_source}{\+\_\+\+\_\+init\+\_\+\+\_\+.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pandas/errors/\+\_\+\+\_\+init\+\_\+\+\_\+.\+py\end{DoxyCompactItemize}
