\doxysection{pandas.\+errors.\+Specification\+Error Class Reference}
\hypertarget{classpandas_1_1errors_1_1SpecificationError}{}\label{classpandas_1_1errors_1_1SpecificationError}\index{pandas.errors.SpecificationError@{pandas.errors.SpecificationError}}


Inheritance diagram for pandas.\+errors.\+Specification\+Error\+:
% FIG 0


Collaboration diagram for pandas.\+errors.\+Specification\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Exception raised by ``agg`` when the functions are ill-specified.

The exception raised in two scenarios.

The first way is calling ``agg`` on a
Dataframe or Series using a nested renamer (dict-of-dict).

The second way is calling ``agg`` on a Dataframe with duplicated functions
names without assigning column name.

Examples
--------
>>> df = pd.DataFrame({'A': [1, 1, 1, 2, 2],
...                    'B': range(5),
...                    'C': range(5)})
>>> df.groupby('A').B.agg({'foo': 'count'}) # doctest: +SKIP
... # SpecificationError: nested renamer is not supported

>>> df.groupby('A').agg({'B': {'foo': ['sum', 'max']}}) # doctest: +SKIP
... # SpecificationError: nested renamer is not supported

>>> df.groupby('A').agg(['min', 'min']) # doctest: +SKIP
... # SpecificationError: nested renamer is not supported
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pandas_2errors_2____init_____8py_source_l00383}{383}} of file \mbox{\hyperlink{pandas_2errors_2____init_____8py_source}{\+\_\+\+\_\+init\+\_\+\+\_\+.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pandas/errors/\+\_\+\+\_\+init\+\_\+\+\_\+.\+py\end{DoxyCompactItemize}
